language: python
python:
  - 2.6
  - 2.7
  
install:
 - pip install coveralls

# change from 'script: python setup.py test' to this
coverage run --source hyperop setup.py test

after_success:
    coveralls